name: Build App
on:
  push:
    branches:
      - master
    tags:
      - "*"

  workflow_dispatch:

jobs:
  prepare:
    name: Prepare App
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-prepare
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install packages
        run: yarn install

      - name: Download binaries
        run: yarn download:binaries

      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: .
          retention-days: 1

  build:
    name: Build ${{ matrix.build-for }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.build-for }}
      cancel-in-progress: true
    needs: prepare
    strategy:
      matrix:
        build-for: [mac, win, linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: workspace

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Build ${{ matrix.build-for }}
        run: yarn build:${{ matrix.build-for }}

      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/${{ matrix.build-for }}/*
